server {
    listen 80;
    server_name acc.iitp.ac.in;
    client_max_body_size 500M;

    # No need for /.well-known/ anymore
    return 301 https://acc.iitp.ac.in$request_uri;
}

server {
    listen 443 ssl;
    server_name acc.iitp.ac.in;

    client_max_body_size 500M;

    # --- SSL CONFIGURATION ---
    # Update these filenames to match EXACTLY what you put in the certs folder
    ssl_certificate     /etc/nginx/ssl/iitp.ac.in-chain.crt; 
    ssl_certificate_key /etc/nginx/ssl/iitp.ac.in_milti_2025.key;

    location / {
        root /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend-acc:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }  


   location /media/ {
        proxy_pass http://minio-acc:9000/;
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_request_buffering off;
        proxy_buffering off;
    }
}
