events {}

http {
  include /etc/nginx/mime.types;

  # General API limit: per IP
  limit_req_zone $binary_remote_addr zone=api_limit:10m rate=100r/s;

  # Stricter limit for auth / sensitive routes
  limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=5r/s;

  include /etc/nginx/conf.d/*.conf;
}
