name: Deploy on Institute VM

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy latest changes
        run: |
          whoami
          echo $HOME
          ls -al ~/.ssh

          cd /home/iitp/Academic-Council-Portal
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

          git pull origin main
          cd client-acc
          npm install
          npm run build